Back to top button
aemsites/ingredion pull request #63
Opened 2024-12-18 15:56 UTC by alexandraa-kupreeva

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #51

Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/
- After: https://issue-51--ingredion--aemsites.aem.live/na/en-us/

2024-12-18 19:11 UTC, varunmitra commented on scripts/delayed.js
@alexandra-kupreeva Can you please move initBackToTop() method to `scripts.js` and add a method invocation to `delayed.js`?
This will allow us to keep `delayed.js` file a lot cleaner and easier to manage.

2024-12-18 19:14 UTC, varunmitra commented on scripts/delayed.js
> +  const createElement = (tag, classNames, textContent = '') => {
`/scripts/dom-helpers.js` already exports several functions for creating desired elements. Please review `dom-helpers.js` and re-use one of the available methods

2024-12-18 19:16 UTC, varunmitra reviewed
rest of the code looks good. with these 2 changes we will be good to go

2024-12-18 19:16 UTC, dave-fink requested changes
- Can you make the text a clickable area as well
- Add user-select: none; so that user can't select the text as well

2025-01-03 10:41 UTC, alexandraa-kupreeva commented on scripts/delayed.js
@varunmitra I moved initBackToTop() to its own module because moving it to `scripts.js` and invoking it from `delayed.js` resulted in a circular dependency.

2025-01-10 13:19 UTC, varunmitra submitted a review, later dismissed

2025-01-28 16:29 UTC, dave-fink commented
@alexandraa-kupreeva can you take a look at this comment?  Once that's resolved I'll mark it as resolved so we can get this merged :) 

![image](https://github.com/user-attachments/assets/9df6a779-db6a-4c68-a9d9-88cf403a8b3e)

2025-01-28 17:35 UTC, merged